# Generated by Django 6.1.1 on 2026-09-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('classification', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('PHISHING', 'Phishing')], default='SAFE', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('string_analysis_detail', models.JSONField(blank=True, default=dict)),
                ('hermes_verification_detail', models.JSONField(blank=True, default=dict)),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_scanned'],
            },
        ),
    ]
