# Generated by Django 6.1.1 on 2026-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_scanlog_html_analysis_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='llm_analysis_detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
