# Generated by Django 6.1.1 on 2026-09-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_add_virustotal_and_mistral_fields'),
        ('logger', '0003_scanlog_llm_analysis_detail'),
    ]

    operations = [
    ]
